on:
  push:
    branches:
      - main

jobs:
  windows_hello:
    runs-on: windows-latest
    steps:
      - run: echo "Hello World from Windows Runner!!"
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event"
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "GitHub Repository URL is ${{ github.repositoryUrl}} and branch is ${{ github.ref_name }} "
      - name: Cloning GitHub Repo 
        uses: actions/checkout@v3
      - name: List files in workspace
        run: ls ${{ github.workspace }}
      - working-directory: ${{env.GITHUB_WORKSPACE}}
        run: ./hello.bat
      - name: List Environment Variables using cmd
        run: set
